---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: contactuiappdeployment
spec:
 replicas: 1
 selector:
   matchLabels:
     run: contactui
 template:
  metadata:
   name: contactui
   labels:
     run: contactui
  spec:
    containers:
    - name: contactuicontainer
      image: krishna0369/frontend-app
      ports:
      - containerPort: 80
      resources:
         limits:
           cpu: 500m
         requests:
           cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
 name: contactuisvc
spec:
  type: LoadBalancer
  selector:
   app: contactui
  ports:
   - port: 80
     targetPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: contactuiappdeployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
...
